[package]
name = "zova"
version = "0.1.0"
edition = "2021"
links = "X11"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.11"
x11 = "2.21.0"

